### ISSUE TITLE
Preservation of metadata

### ISSUE THREAD

**Issue by eturkes** [niaid/sitk-ibex#39]
Thanks again for the TIFF image fix. I ran through the pipeline and I noticed that the resultant TIFF image I made from the resample command contains no metadata. After investigating, this appears to be the case in the example spleen .nrrd image as well. I attached an image of the metadata of this example from ImageJ, where the original is on the left, the resampled right. The resampled lacks the imaris_channels_information. This kind of information is important for our usecase as we want want to be able to visualize other channels besides the one used for registration. Is this possible with your software?

![Screenshot_20220518_140624](https://user-images.githubusercontent.com/25193231/169115223-7ebce7f7-81cd-40d0-83f4-54d150e67677.png)

**Comment by zivy** [comment]
Hello @eturkes,

The focus of the sitk-ibex repository was on the algorithmic side, so details such as copying over the image meta-data after resampling are outside the scope. 

Having said this, we have developed software that builds on the sitk-ibex package and supports an interface that is more in line with microscopy workflows, GUI and the output combines all resampled images into one and copies over channel information. Specifically, see the [imaris extensions](https://github.com/niaid/imaris_extensions) repository, `XTRegisterSameChannel` application. The only requirement there is that the files are in the ims format (I believe Fiji can export to ims). While originally designed to work as plugins for the Imaris program, these applications can also be run in standalone mode, so you do not need the Imaris software itself to take advantage of the extensions.

**Comment by eturkes** [comment]
Dear @zivy 

Thank you very much for the informative reply. I will certainly explore your suggestion and see if we can get our data into a suitable format. Really hoping so, your extensions repo looks quite developed!
